version: 2

sources:
  - name: staging
    database: vast-signifier-375221
    schema: dezoomcamp

    tables:
    - name: fhv_tripdata

models:
  - name: stg_fhv_tripdata
    description: >
      Trips from fhv.
    columns:
      - name: dispatching_base_number
        description: The number of the dispatching base.
      - name: pickup_datetime
        description: The dateime of the trip start.
      - name: dropoff_datetime
        description: The dateime of the trip end.
      - name: pickup_locationid
        description: the id of the pickup location.
      - name: dropoff_locationid
        description: the id of the dropoff location.
      - name: sr_flag
        description: a flag.
      - name: affiliated_base_number
        description: the number of the affiliated base.
      - name: trip_id
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
        description: the id of the trip.